/*
@TargetNode='localhost'
@GeneratedBy=t-shvohra
@GenerationDate=06/16/2022 15:56:41
@GenerationHost=DESKTOP-PNMOTMT
*/

instance of NewFile as $NewFile1ref
{
ModuleVersion = "1.0.0";
 path = "/tmp/test.txt";
 ensure = "Present";
 ModuleName = "NewFile";
 ResourceID = "[NewFile]test";
 content = "DSC Rocks!";
 SourceInfo = "C:\\Users\\t-shvohra\\Desktop\\azure-policy-ramp\\demo-config\\demo-config.ps1::13::10::NewFile";
 ConfigurationName = "basic";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="t-shvohra";

                        GenerationDate="06/16/2022 15:56:41";

                        GenerationHost="DESKTOP-PNMOTMT";

                        Name="basic";

                    };
