trigger: 
  - main

stages:
  - stage: Build
    dependsOn: []

    jobs:
      - job: ConfigPackaging
        displayName: Configuration Package Creation
        pool: 
          vmImage: windows-2022

        steps:
          - task: PowerShell@2
            displayName: Setting Modules and Compiling
            inputs:
              pwsh: true
              targetType: 'inline'
              script: |
                find-module PSDesiredStateConfiguration | install-module -Force
                find-module PSDSCResources | install-module -Force
                find-module GuestConfiguration | install-module -Force
                find-module SChannelDsc | install-module -Force
                
                .\tls-config\tls.ps1
                
                dir

                dir tls

                New-GuestConfigurationPackage -Name 'tls-secure' -Configuration './tls/localhost.mof' -Type AuditAndSet -Force

          # - task: PowerShell@2
          #   displayName: Creating zip package
          #   inputs:
          #     targetType: 'inline'
          #     script: |
          #       New-GuestConfigurationPackage -Name 'tls-secure' -Configuration './tls/localhost.mof' -Type AuditAndSet -Force




              