trigger: 
  - main

stages:
  - stage: Build
    dependsOn: []

    jobs:
      - job: ConfigPackaging
        displayName: Configuration Package Creation
        pool: 
          vmImage: windows-2022

        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                find-module PSDesiredStateConfiguration | install-module -Force
                find-module PSDSCResources | install-module -Force
                find-module GuestConfiguration | install-module -Force
                find-module SChannelDsc | install-module -Force
                
                .\tls-config\tls.ps1
                
                dir
              pwsh: true

                dir tls

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                New-GuestConfigurationPackage -Name 'tls-secure' -Configuration './tls/localhost.mof' -Type AuditAndSet -Force




              